### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
I have added `</br>` tag to make separate lines for `dashboard` and `memphis broker` URLs.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@idanasulinmemphis Please review this PR.

**Comment by SaptarshiSarkar12** [comment]
@idanasulinmemphis @yanivbh1 please review this PR.

**Review by idanasulinmemphis — APPROVED** [review]
@SaptarshiSarkar12 thanks for this one, approved

**Comment by SaptarshiSarkar12** [comment]
@idanasulinmemphis Welcome.
Thanks for reviewing.

**Pull request merged**
