### PR TITLE
Produceripchange

### PR DESCRIPTION
**Pull request by erankitcs**
Fix for bug #247 

1. Enhanced handlers/connections.go Function -  ReliveConnection to receive client Address as well.
2. Enhanced tcp_server/tcp_server.go  Function- handleConnectMessage to pass Client Address during ReliveConnection call.

### CODE REVIEW

**Comment by yanivbh1** [comment]
@erankitcs Looks great!
Waiting for @idanasulinmemphis review

**Comment by idanasulinmemphis** [comment]
Hello @erankitcs and thank you for the PR
Regarding your code -
client address field is getting initialized once a new client connect with memphis. Relive connection getting called in case of memphis failure, that means on reconnect attempts of the client. In such case we don’t need to update the client address.

we will be glad you to try to fix this bug which is in the same area.

https://github.com/memphisdev/memphis-broker/issues/247

any way I’d like to thank you for your time and telling you that we are blessed o have you as an active contributor.

**Comment by erankitcs** [comment]
Thanks a lot @idanasulinmemphis  for the review. I really like the idea and am happy to contribute as much as possible from my side.
In regards to #247  , I revisited the code again. It looks like Connection.go will relive the connection if connectionId already exists otherwise it will create a new connection with a new connectionID which will store the new IP address coming from the consumer or producer. And if a newly created connectionID is coming during consumer or producer creation then new IP address will appear. 

Looks like an issue upstream of the broker. Any thoughts ??

**Comment by idanasulinmemphis** [comment]
Please let me explain the flow.
new client call "connect" => broker issues a connectionId, stores it alongside the client IP and send it to the client => client saves it in its main memory.
2 scenarios are possible from that point:
1. client application crash - here connectionId  is lost since the client saves it in its main memory, hence when the client will restart it will connect again and will get a new connectionId -> broker creates a new connection record with the client IP
2. broker crash -> here the client notice this failure and tries to reconnect to a different broker (in case memphis is in cluster mode), in case it finds an available broker it sends its old connectionId and the broker just update the connection status, but the IP remains the same, since the client application didn't crash.

Regarding #247, the case here I think is: create a producer with some IP => delete it => create another producer with the same name from a different IP
same for consumers with the same CG name.

**Comment by erankitcs** [comment]
Thanks, @idanasulinmemphis for explaining the flow.
As per your suggested scenario, when another producer will try to connect with same name from different IP. There could be two possible scenarios..
1. it is passing the same connectionID, so as per tcp_server.go , 109 connectExit check will pass and it will become a relive scenario.
2. it is not passing connectionID or connectionID which does not exist, then it will go for new connectionID and then we will have new IP saved along with that.

This particular PR is solving scenario-1 where relive is happening because the same connectionID passed when even though it is connecting from different IP.

Another solution could be to enhance connectionExist check to match ClientAddress as well so that if it does not match, we can safely go for a new connection.

**Comment by idanasulinmemphis** [comment]
I don't think such a scenario is possible since the following reasons:
1. 2 (not deleted/destroyed) producers is not possible
2. connectionId is unique per connection, so it is not possible 2 different producers to be connected with the same connectionId

**Comment by erankitcs** [comment]
Thanks, @idanasulinmemphis  Looks like we need to simulate this scenario for a better understanding of where is the issue. It's hard to simulate on a local machine. I will try to deploy this into AWS and simulate this.

**Comment by yanivbh1** [comment]
Hey @erankitcs, any suggestions on how can we make it easier to run a dev environment of the broker?

**Comment by idanasulinmemphis** [comment]
Closing it since we are changing a bit our branches structure, in case it is still relevant from your side please open it again to branch master

**Pull request closed without merging**
